# permissions for end users to view systeminformations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: systeminformation-viewer-role
rules:
- apiGroups:
  - system.k8s.nokia-ipfabric-operator-kb.fnetworks.tf
  resources:
  - systeminformations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - system.k8s.nokia-ipfabric-operator-kb.fnetworks.tf
  resources:
  - systeminformations/status
  verbs:
  - get
